# SPDX-License-Identifier: PMPL-1.0-or-later
# Mirror to multiple Git forges
name: Mirror Sync

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions: read-all

jobs:
  mirror-gitlab:
    runs-on: ubuntu-latest
    if: vars.GITLAB_MIRROR_ENABLED == 'true'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITLAB_SSH_KEY }}

      - run: |
          git remote add gitlab git@gitlab.com:hyperpolymath/${{ github.event.repository.name }}.git || true
          git push gitlab --all --force
          git push gitlab --tags --force

  mirror-bitbucket:
    runs-on: ubuntu-latest
    if: vars.BITBUCKET_MIRROR_ENABLED == 'true'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Mirror to Bitbucket
        uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
        with:
          ssh-private-key: ${{ secrets.BITBUCKET_SSH_KEY }}

      - run: |
          git remote add bitbucket git@bitbucket.org:hyperpolymath/${{ github.event.repository.name }}.git || true
          git push bitbucket --all --force
          git push bitbucket --tags --force

  mirror-codeberg:
    runs-on: ubuntu-latest
    if: vars.CODEBERG_MIRROR_ENABLED == 'true'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
        with:
          ssh-private-key: ${{ secrets.CODEBERG_SSH_KEY }}

      - run: |
          git remote add codeberg git@codeberg.org:hyperpolymath/${{ github.event.repository.name }}.git || true
          git push codeberg --all --force
          git push codeberg --tags --force

  mirror-sourcehut:
    runs-on: ubuntu-latest
    if: vars.SOURCEHUT_MIRROR_ENABLED == 'true'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Mirror to SourceHut
        uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
        with:
          ssh-private-key: ${{ secrets.SOURCEHUT_SSH_KEY }}

      - run: |
          git remote add srht git@git.sr.ht:~hyperpolymath/${{ github.event.repository.name }} || true
          git push srht --all --force
          git push srht --tags --force
