// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by hypatia-abi-gen from src/Hypatia/ABI/Types.idr
// ABI source blob: 788493e6f54b6d436ea551dbb5d34c6bc0d819ab
// DO NOT EDIT -- run `just abi-gen` and commit the result.

//! The sixteen-protocol wire contract, generated from the normative
//! Idris2 ABI. `unified-api-adapter.zig` re-exports these declarations
//! and keeps its own hand-written tests.

pub const Connector = enum(u8) {
    grpc = 0,
    graphql = 1,
    rest = 2,
    flatbuffers = 3,
    bebop = 4,
    jsonrpc = 5,
    websocket = 6,
    mqtt = 7,
    trpc = 8,
    capnproto = 9,
    soap = 10,
    verisimdb_rest = 11,
    bsp = 12,
    scip = 13,
    ipfs = 14,
    arrow_flight = 15,

    /// Stable wire name. Load-bearing: do not rename.
    pub fn name(self: Connector) [*:0]const u8 {
        return switch (self) {
            .grpc => "grpc",
            .graphql => "graphql",
            .rest => "rest",
            .flatbuffers => "flatbuffers",
            .bebop => "bebop",
            .jsonrpc => "jsonrpc",
            .websocket => "websocket",
            .mqtt => "mqtt",
            .trpc => "trpc",
            .capnproto => "capnproto",
            .soap => "soap",
            .verisimdb_rest => "verisimdb-rest",
            .bsp => "bsp",
            .scip => "scip",
            .ipfs => "ipfs",
            .arrow_flight => "arrow-flight",
        };
    }

    /// The connector's implementation module, selected at comptime.
    pub fn module(comptime self: Connector) type {
        return switch (self) {
            .grpc => @import("connectors/grpc.zig"),
            .graphql => @import("connectors/graphql.zig"),
            .rest => @import("connectors/rest.zig"),
            .flatbuffers => @import("connectors/flatbuffers.zig"),
            .bebop => @import("connectors/bebop.zig"),
            .jsonrpc => @import("connectors/jsonrpc.zig"),
            .websocket => @import("connectors/websocket.zig"),
            .mqtt => @import("connectors/mqtt.zig"),
            .trpc => @import("connectors/trpc.zig"),
            .capnproto => @import("connectors/capnproto.zig"),
            .soap => @import("connectors/soap.zig"),
            .verisimdb_rest => @import("connectors/verisimdb_rest.zig"),
            .bsp => @import("connectors/bsp.zig"),
            .scip => @import("connectors/scip.zig"),
            .ipfs => @import("connectors/ipfs.zig"),
            .arrow_flight => @import("connectors/arrow_flight.zig"),
        };
    }
};

/// Derived from the enum itself, never a hand-written literal.
pub const CONNECTOR_COUNT: usize = @typeInfo(Connector).@"enum".fields.len;

/// Every connector, in wire order.
pub const ALL: [CONNECTOR_COUNT]Connector = .{
    .grpc,
    .graphql,
    .rest,
    .flatbuffers,
    .bebop,
    .jsonrpc,
    .websocket,
    .mqtt,
    .trpc,
    .capnproto,
    .soap,
    .verisimdb_rest,
    .bsp,
    .scip,
    .ipfs,
    .arrow_flight,
};

/// Port layout: `base_port + wire_id + 1`.
pub fn portFor(base_port: u16, c: Connector) u16 {
    return base_port + @as(u16, @intFromEnum(c)) + 1;
}
