# SPDX-License-Identifier: MPL-2.0
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/adapters"
      - "/cli"
      - "/data"
      - "/fixer"
      - "/integration"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      shared-rust-dependencies:
        group-by: dependency-name

  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      elixir-minor:
        update-types: ["minor", "patch"]
