;; SPDX-License-Identifier: PMPL-1.0
;; ECOSYSTEM.scm - Project relationship mapping for cicd-hyper-a

(ecosystem
  (version "1.0")
  (name "cicd-hyper-a")
  (type "intelligence-platform")
  (purpose "Neurosymbolic CI/CD intelligence platform that learns patterns and distills them into verified, fast-acting rules")

  (position-in-ecosystem
    (role "central-intelligence")
    (layer "platform")
    (description "The brain of hyperpolymath CI/CD - combines neural learning with symbolic reasoning to generate and verify repository rules"))

  (related-projects
    (downstream
      (robot-repo-automaton
        (relationship "action-executor")
        (description "Executes rules and fixes generated by cicd-hyper-a")
        (integration "Consumes rulesets via registry API, applies hooks and fixes"))
      (gitbot-fleet
        (relationship "specialized-consumers")
        (description "Fleet of bots that use cicd-hyper-a rules for specialized checks")
        (integration "Bots query ruleset registry for domain-specific rules")))
    (sibling
      (gitvisor
        (relationship "visualization-layer")
        (description "Dashboard for visualizing rule application and repository health"))
      (rhodium-standard-repositories
        (relationship "standards-definition")
        (description "RSR spec that informs rule content - cicd-hyper-a enforces RSR via rules"))
      (palimpsest-license
        (relationship "philosophical-foundation")
        (description "Philosophical principles underlying rule design")))
    (integration-targets
      (github (relationship "forge-target") (adapter "adapters/github.rs"))
      (gitlab (relationship "forge-target") (adapter "adapters/gitlab.rs"))
      (bitbucket (relationship "forge-target") (adapter "adapters/bitbucket.rs"))
      (codeberg (relationship "forge-target") (adapter "planned"))
      (sourcehut (relationship "forge-target") (adapter "planned"))
      (radicle (relationship "p2p-federation") (adapter "adapters/radicle.rs"))))

  (architecture-layers
    (verification-layer
      (tech "Haskell")
      (components "Type-safe DSL" "Property testing" "Liquid Haskell proofs")
      (purpose "Ensure rules are correct before deployment"))
    (learning-layer
      (tech "Neural")
      (components "Pattern recognition" "Anomaly detection" "Rule distillation")
      (purpose "Learn from CI/CD failures to generate new rules"))
    (symbolic-layer
      (tech "Logtalk/Prolog")
      (components "Declarative rules" "Inference engine" "Fast execution")
      (purpose "Execute rules with sub-millisecond latency"))
    (data-layer
      (tech "ArangoDB, Dragonfly, Radicle")
      (components "Graph storage" "Distributed cache" "P2P sync")
      (purpose "Store relationships and enable fast lookups"))
    (action-layer
      (tech "robot-repo-automaton")
      (components "Hooks" "Diagnostics" "Auto-repair")
      (purpose "Apply rules to actual repositories")))

  (what-this-is
    "The intelligence center for hyperpolymath repository automation"
    "A neural-symbolic hybrid that learns patterns and produces verified rules"
    "A Haskell-based registry for type-safe, formally verified rulesets"
    "A Logtalk/Prolog engine for fast rule execution"
    "A multi-forge platform supporting GitHub, GitLab, Bitbucket, and more"
    "The source of truth for what rules exist and how they behave")

  (what-this-is-not
    "Not the action executor - that is robot-repo-automaton"
    "Not a single-purpose bot - those are in gitbot-fleet"
    "Not a dashboard - that is gitvisor"
    "Not the standards definition - that is rhodium-standard-repositories"
    "Not just a linter - it learns, verifies, and evolves rules"))
