#!/usr/bin/env bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# fix-dependabot.sh — Add .github/dependabot.yml for automated dependency updates
# Recipe: recipe-add-dependabot (confidence: 0.95, auto_fixable: true)
#
# Usage: fix-dependabot.sh <repo-path>

set -euo pipefail

REPO="${1:?Usage: fix-dependabot.sh <repo-path>}"
TARGET="${REPO}/.github/dependabot.yml"

if [[ -f "$TARGET" ]]; then
  echo "[fix-dependabot] Already exists: ${TARGET}"
  exit 0
fi

mkdir -p "${REPO}/.github"

# Detect ecosystems present in the repo
ecosystems=()
[[ -f "${REPO}/Cargo.toml" ]] && ecosystems+=("cargo")
[[ -f "${REPO}/mix.exs" ]] && ecosystems+=("mix")
[[ -f "${REPO}/deno.json" || -f "${REPO}/deno.jsonc" ]] && ecosystems+=("npm")
[[ -f "${REPO}/gleam.toml" ]] && ecosystems+=("hex")
[[ -f "${REPO}/build.zig" ]] && ecosystems+=("zig")  # No dependabot support yet, skip
[[ -d "${REPO}/.github/workflows" ]] && ecosystems+=("github-actions")

cat > "$TARGET" <<'YAML'
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by Hypatia fix-dependabot.sh
version: 2
updates:
YAML

for eco in "${ecosystems[@]}"; do
  case "$eco" in
    cargo)
      cat >> "$TARGET" <<'YAML'
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
YAML
      ;;
    mix)
      cat >> "$TARGET" <<'YAML'
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
YAML
      ;;
    npm)
      cat >> "$TARGET" <<'YAML'
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
YAML
      ;;
    hex)
      cat >> "$TARGET" <<'YAML'
  - package-ecosystem: "hex"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
YAML
      ;;
    github-actions)
      cat >> "$TARGET" <<'YAML'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
YAML
      ;;
  esac
done

# If no ecosystems detected, at least add github-actions
if [[ ${#ecosystems[@]} -eq 0 ]]; then
  cat >> "$TARGET" <<'YAML'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
YAML
fi

echo "[fix-dependabot] Created ${TARGET} with ${#ecosystems[@]} ecosystem(s)"
