#!/usr/bin/env bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# fix-scorecard-ci-tests.sh — Add minimal CI test workflow (SC-007)
# Recipe: recipe-scorecard-ci-tests (confidence: 0.88, auto_fixable: true)
#
# Adds a language-appropriate CI workflow if none exists.
# Priority: mix.exs → Cargo.toml → deno.json → gleam.toml → generic shell.
#
# Usage: fix-scorecard-ci-tests.sh <repo-path>

set -euo pipefail

REPO="${1:?Usage: fix-scorecard-ci-tests.sh <repo-path>}"
WF_DIR="${REPO}/.github/workflows"

# Already has CI if any workflow runs tests
if ls "${WF_DIR}"/*.yml "${WF_DIR}"/*.yaml 2>/dev/null | xargs grep -l 'mix test\|cargo test\|deno test\|gleam test' 2>/dev/null | grep -q .; then
  echo "[fix-scorecard-ci-tests] CI test workflow already present"
  exit 0
fi

mkdir -p "$WF_DIR"

if [[ -f "${REPO}/mix.exs" ]]; then
  # Delegate to the Elixir CI script
  "$(dirname "$0")/fix-add-elixir-ci.sh" "$REPO"
elif [[ -f "${REPO}/Cargo.toml" ]]; then
  cat > "${WF_DIR}/ci.yml" <<'YAML'
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by Hypatia fix-scorecard-ci-tests.sh
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # stable
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
      - run: cargo test --all-features
YAML
  echo "[fix-scorecard-ci-tests] Created Rust CI workflow"
elif [[ -f "${REPO}/deno.json" || -f "${REPO}/deno.jsonc" ]]; then
  cat > "${WF_DIR}/ci.yml" <<'YAML'
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by Hypatia fix-scorecard-ci-tests.sh
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: denoland/setup-deno@e95548ea6a9f30ee87d9e2cc7a11f29f71ba31e4 # v2.0.3
      - run: deno test --allow-all
YAML
  echo "[fix-scorecard-ci-tests] Created Deno CI workflow"
elif [[ -f "${REPO}/gleam.toml" ]]; then
  cat > "${WF_DIR}/ci.yml" <<'YAML'
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by Hypatia fix-scorecard-ci-tests.sh
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        with:
          otp-version: "27"
      - run: gleam test
YAML
  echo "[fix-scorecard-ci-tests] Created Gleam CI workflow"
else
  cat > "${WF_DIR}/ci.yml" <<'YAML'
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by Hypatia fix-scorecard-ci-tests.sh
# TODO: replace the test step with your project's test command
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run tests
        run: echo "TODO: add test command"
YAML
  echo "[fix-scorecard-ci-tests] Created generic CI workflow placeholder"
fi
