#!/usr/bin/env bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# fix-scorecard-sbom.sh — Generate a CycloneDX SBOM (SC-018)
# Recipe: recipe-scorecard-sbom (confidence: 0.85, auto_fixable: true)
#
# Generates a minimal CycloneDX SBOM and adds a workflow to regenerate on release.
# Supports Rust (cargo-cyclonedx) and Elixir (mix sbom via mix_sbom).
#
# Usage: fix-scorecard-sbom.sh <repo-path>

set -euo pipefail

REPO="${1:?Usage: fix-scorecard-sbom.sh <repo-path>}"
WF_DIR="${REPO}/.github/workflows"

mkdir -p "$WF_DIR"

if [[ -f "${REPO}/Cargo.toml" ]]; then
  cat > "${WF_DIR}/sbom.yml" <<'YAML'
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by Hypatia fix-scorecard-sbom.sh
name: SBOM

on:
  push:
    branches: [main]
  release:
    types: [published]

permissions: read-all

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # stable
      - name: Install cargo-cyclonedx
        run: cargo install cargo-cyclonedx
      - name: Generate SBOM
        run: cargo cyclonedx --format json --output-cdx
      - name: Upload SBOM
        uses: actions/upload-artifact@ea165f8d65b6e5fe5dd2bbaa5aad64fe4e76f5b1 # v4.6.2
        with:
          name: sbom
          path: "*.cdx.json"
YAML
  echo "[fix-scorecard-sbom] Created Rust SBOM generation workflow"
elif [[ -f "${REPO}/mix.exs" ]]; then
  cat > "${WF_DIR}/sbom.yml" <<'YAML'
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by Hypatia fix-scorecard-sbom.sh
name: SBOM

on:
  push:
    branches: [main]

permissions: read-all

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        with:
          otp-version: "27"
          elixir-version: "1.17"
      - run: mix deps.get
      - run: mix sbom.cyclonedx --format json --output bom.json || echo "Install :mix_sbom in deps"
      - uses: actions/upload-artifact@ea165f8d65b6e5fe5dd2bbaa5aad64fe4e76f5b1 # v4.6.2
        with:
          name: sbom
          path: bom.json
YAML
  echo "[fix-scorecard-sbom] Created Elixir SBOM workflow"
else
  cat > "${WF_DIR}/sbom.yml" <<'YAML'
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by Hypatia fix-scorecard-sbom.sh
name: SBOM

on:
  push:
    branches: [main]

permissions: read-all

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Generate SBOM
        run: echo "TODO: add SBOM generation for this project type"
YAML
  echo "[fix-scorecard-sbom] Created SBOM workflow stub"
fi
