#!/usr/bin/env bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# fix-scorecard-signed-releases.sh — Add Sigstore cosign release signing (SC-019)
# Recipe: recipe-scorecard-signed-releases (confidence: 0.82, auto_fixable: true)
#
# Adds a GitHub Actions release workflow that signs release artifacts with
# sigstore/cosign using GitHub's OIDC token (keyless signing).
#
# Usage: fix-scorecard-signed-releases.sh <repo-path>

set -euo pipefail

REPO="${1:?Usage: fix-scorecard-signed-releases.sh <repo-path>}"
WF_DIR="${REPO}/.github/workflows"
TARGET="${WF_DIR}/sign-release.yml"

if [[ -f "$TARGET" ]]; then
  echo "[fix-scorecard-signed-releases] Sign workflow already exists: ${TARGET}"
  exit 0
fi

mkdir -p "$WF_DIR"

cat > "$TARGET" <<'YAML'
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by Hypatia fix-scorecard-signed-releases.sh
# Keyless release signing via sigstore/cosign + GitHub OIDC
name: Sign Release

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install cosign
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb39f4173e6afd6a5 # v3.8.1

      - name: Sign release artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Download all release assets
          gh release download "${{ github.event.release.tag_name }}" -D ./artifacts
          # Sign each artifact with cosign
          for file in ./artifacts/*; do
            cosign sign-blob --yes --bundle "${file}.bundle" "$file"
            gh release upload "${{ github.event.release.tag_name }}" "${file}.bundle"
          done
YAML

echo "[fix-scorecard-signed-releases] Created release signing workflow using cosign keyless OIDC"
