#!/usr/bin/env bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# fix-add-elixir-ci.sh — Add standard Elixir CI workflow
# Recipe: recipe-add-elixir-ci (confidence: 0.92, auto_fixable: true)
#
# Adds .github/workflows/elixir.yml with mix deps.get, format check, and test.
#
# Usage: fix-add-elixir-ci.sh <repo-path>

set -euo pipefail

REPO="${1:?Usage: fix-add-elixir-ci.sh <repo-path>}"
TARGET="${REPO}/.github/workflows/elixir.yml"

[[ -f "${REPO}/mix.exs" ]] || { echo "[fix-add-elixir-ci] No mix.exs found — skipping"; exit 0; }

if [[ -f "$TARGET" ]]; then
  echo "[fix-add-elixir-ci] Already exists: ${TARGET}"
  exit 0
fi

mkdir -p "${REPO}/.github/workflows"

ELIXIR_VERSION="1.17"
OTP_VERSION="27"
if [[ -f "${REPO}/.tool-versions" ]]; then
  _ex=$(grep '^elixir' "${REPO}/.tool-versions" | awk '{print $2}' | head -1)
  _otp=$(grep '^erlang' "${REPO}/.tool-versions" | awk '{print $2}' | head -1)
  [[ -n "$_ex" ]] && ELIXIR_VERSION="$_ex"
  [[ -n "$_otp" ]] && OTP_VERSION="$_otp"
fi

cat > "$TARGET" <<YAML
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by Hypatia fix-add-elixir-ci.sh
name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        with:
          elixir-version: '${ELIXIR_VERSION}'
          otp-version: '${OTP_VERSION}'
      - name: Restore dependencies cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e88c7 # v4.2.3
        with:
          path: deps
          key: \${{ runner.os }}-mix-\${{ hashFiles('**/mix.lock') }}
          restore-keys: \${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Check formatting
        run: mix format --check-formatted
      - name: Compile
        run: mix compile --warnings-as-errors
      - name: Run tests
        run: mix test
YAML

echo "[fix-add-elixir-ci] Created ${TARGET} (Elixir ${ELIXIR_VERSION}, OTP ${OTP_VERSION})"
