#!/usr/bin/env bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# fix-scorecard-cii-best-practices.sh — Generate CII Best Practices guidance (SC-009)
# Recipe: recipe-scorecard-cii-best-practices (auto_fixable: false)
#
# Produces a checklist of steps needed to earn the CII Best Practices badge.
# Registration and badge award require human action at bestpractices.dev.
#
# Usage: fix-scorecard-cii-best-practices.sh <repo-path>

set -euo pipefail

REPO="${1:?Usage: fix-scorecard-cii-best-practices.sh <repo-path>}"
REPORT="${REPO}/.hypatia-cii-best-practices-checklist.md"

cat > "$REPORT" <<'MD'
# CII Best Practices Checklist

Generated by Hypatia fix-scorecard-cii-best-practices.sh

## Registration

1. Visit https://bestpractices.coreinfrastructure.org/en/projects/new
2. Enter this repository's GitHub URL
3. Work through the questionnaire

## Quick wins (usually already done)

- [ ] CONTRIBUTING.md or CONTRIBUTING.adoc present
- [ ] SECURITY.md present with vulnerability reporting policy
- [ ] LICENSE file present (MPL-2.0 / PMPL-1.0-or-later)
- [ ] README with project description

## Code quality criteria

- [ ] Automated test suite present and run in CI
- [ ] Static analysis (CodeQL, Clippy, etc.) in CI
- [ ] No compiler warnings on clean build

## Security criteria

- [ ] Dependency update automation (Dependabot)
- [ ] No known unpatched CVEs in dependencies
- [ ] HTTPS for all external communications

## Use the cii-registrar tool

```bash
cii-registrar register --repo <this-repo-url>
```

See tools/cii-registrar/ in the hypatia workspace for automation support.
MD

echo "[fix-scorecard-cii-best-practices] Checklist written to ${REPORT}"
echo "[fix-scorecard-cii-best-practices] Human action required: register at bestpractices.coreinfrastructure.org"
