#!/usr/bin/env bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# fix-sast-workflow.sh — Add CodeQL static analysis workflow
# Recipe: recipe-add-sast-workflow (confidence: 0.90, auto_fixable: true)
#
# Detects repo languages and generates appropriate CodeQL matrix.
#
# Usage: fix-sast-workflow.sh <repo-path>

set -euo pipefail

REPO="${1:?Usage: fix-sast-workflow.sh <repo-path>}"
TARGET="${REPO}/.github/workflows/codeql.yml"

if [[ -f "$TARGET" ]]; then
  echo "[fix-sast-workflow] Already exists: ${TARGET}"
  exit 0
fi

mkdir -p "${REPO}/.github/workflows"

# Detect languages for CodeQL matrix
languages=()
# JavaScript/TypeScript (includes ReScript compiled output)
if find "$REPO" -maxdepth 3 -name "*.js" -o -name "*.mjs" -o -name "*.res" 2>/dev/null | grep -q .; then
  languages+=("javascript-typescript")
fi
# Ruby
if find "$REPO" -maxdepth 3 -name "*.rb" 2>/dev/null | grep -q .; then
  languages+=("ruby")
fi

# Default to actions-only if no supported language detected
if [[ ${#languages[@]} -eq 0 ]]; then
  languages+=("actions")
fi

# Build matrix string
matrix_langs=$(printf ", '%s'" "${languages[@]}")
matrix_langs="[${matrix_langs:2}]"

cat > "$TARGET" <<EOF
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by Hypatia fix-sast-workflow.sh
name: "CodeQL"

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 6 * * 1'

permissions: read-all

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ${matrix_langs}

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@6624720a57d4c312633c7b953db2f2da5bcb4c3a # v3
        with:
          languages: \${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@6624720a57d4c312633c7b953db2f2da5bcb4c3a # v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@6624720a57d4c312633c7b953db2f2da5bcb4c3a # v3
        with:
          category: "/language:\${{ matrix.language }}"
EOF

echo "[fix-sast-workflow] Created ${TARGET} with languages: ${matrix_langs}"
