# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>

defmodule Hypatia.Rules.ActionsLock do
  @moduledoc """
  Strict local validation for machine-generated `gh actions-lock` v0.0.2 files.

  This module validates lockfile *shape and association*. It does not replace
  `gh actions-lock --verify`, which remains authoritative for resolving refs
  against GitHub. A symbolic action is accepted locally only when the complete
  lock is valid, the current workflow lists that exact normalized ref, and the
  matching dependency carries a canonical `sha1-<40 hex>` commit.

  The parser is deliberately line-oriented. `actions.lock` is generated by a
  single tool with a versioned stable format, and Hypatia must not add a general
  YAML dependency merely to consume that format. Unknown or malformed v0.0.2
  lines fail closed rather than being guessed at.
  """

  @supported_version "v0.0.2"
  @action_ref ~r/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.\/-]+@[^\s':]+$/
  @dependency_key ~r/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+@[^\s':]+$/
  @sha_ref ~r/^[0-9A-Fa-f]{40}$/

  defstruct version: nil, workflows: %{}, dependencies: %{}

  @type dependency :: %{
          ref: String.t(),
          commit: String.t(),
          owner_id: pos_integer(),
          repo_id: pos_integer(),
          uses: MapSet.t(String.t())
        }
  @type t :: %__MODULE__{
          version: String.t(),
          workflows: %{String.t() => MapSet.t(String.t())},
          dependencies: %{String.t() => dependency()}
        }

  @doc """
  Parse and validate a complete v0.0.2 lockfile.

  Returns `{:error, reason}` for missing, unsupported, malformed, incomplete,
  duplicate, or contradictory input. One bad dependency invalidates the whole
  lock so callers cannot silently accept the remaining entries.
  """
  @spec parse(term()) :: {:ok, t()} | {:error, term()}
  def parse(content) when is_binary(content) and byte_size(content) > 0 do
    initial = %{
      section: :preamble,
      version: nil,
      workflows: %{},
      current_workflow: nil,
      dependencies: %{},
      current_dependency: nil
    }

    content
    |> String.split("\n")
    |> Enum.with_index(1)
    |> Enum.reduce_while({:ok, initial}, fn {raw_line, line_number}, {:ok, state} ->
      line = String.trim_trailing(raw_line, "\r")

      case consume_line(line, line_number, state) do
        {:ok, next} -> {:cont, {:ok, next}}
        {:error, _reason} = error -> {:halt, error}
      end
    end)
    |> finish()
  end

  def parse(_), do: {:error, :missing_or_nonbinary_lock}

  @doc """
  Whether `slug` is validly locked for `workflow_path`.

  A lock entry for another workflow never authorizes the current workflow.
  Basenames are resolved under `.github/workflows/` for compatibility with the
  workflow-audit caller, which loads files by basename.
  """
  @spec pinned?(t() | nil, String.t(), String.t()) :: boolean()
  def pinned?(%__MODULE__{} = lock, workflow_path, slug)
      when is_binary(workflow_path) and is_binary(slug) do
    path = normalise_workflow_path(workflow_path)
    ref = normalise_ref(slug)

    lock.workflows
    |> Map.get(path, MapSet.new())
    |> MapSet.member?(ref) and Map.has_key?(lock.dependencies, ref)
  end

  def pinned?(_, _, _), do: false

  @doc """
  Return dependency refs from a fully validated lock.

  This exists only for compatibility with the former global `locked_refs/1`
  API. Security decisions must use `pinned?/3`, which also checks workflow
  association.
  """
  @spec dependency_refs(t()) :: MapSet.t(String.t())
  def dependency_refs(%__MODULE__{} = lock) do
    lock.dependencies |> Map.keys() |> MapSet.new()
  end

  @doc """
  Normalize an action slug to the root `owner/repository@ref` lock key.
  """
  @spec normalise_ref(String.t()) :: String.t()
  def normalise_ref(slug) when is_binary(slug) do
    case String.split(slug, "@", parts: 2) do
      [path, ref] ->
        owner_repo = path |> String.split("/") |> Enum.take(2) |> Enum.join("/")
        String.downcase(owner_repo) <> "@" <> ref

      _ ->
        String.downcase(slug)
    end
  end

  defp normalise_workflow_path(path) do
    normalized = String.replace(path, "\\", "/")

    if String.starts_with?(normalized, ".github/workflows/") do
      normalized
    else
      ".github/workflows/" <> Path.basename(normalized)
    end
  end

  defp consume_line(line, _line_number, state) when line == "", do: {:ok, state}

  defp consume_line("#" <> _comment, _line_number, state), do: {:ok, state}

  defp consume_line(line, line_number, %{section: :preamble} = state) do
    cond do
      match = Regex.run(~r/^version: '([^']+)'$/, line) ->
        case match do
          [_, @supported_version] when is_nil(state.version) ->
            {:ok, %{state | version: @supported_version}}

          [_, @supported_version] ->
            line_error(line_number, :duplicate_version)

          [_, version] ->
            line_error(line_number, {:unsupported_version, version})
        end

      line == "workflows:" and state.version == @supported_version ->
        {:ok, %{state | section: :workflows}}

      true ->
        line_error(line_number, :expected_version_or_workflows)
    end
  end

  defp consume_line(line, line_number, %{section: :workflows} = state) do
    cond do
      line == "dependencies:" ->
        {:ok, %{state | section: :dependencies, current_workflow: nil}}

      match = Regex.run(~r/^    '(\.github\/workflows\/[^']+\.(?:yml|yaml))': \[\]$/, line) ->
        [_, path] = match
        put_workflow(state, path, false, line_number)

      match = Regex.run(~r/^    '(\.github\/workflows\/[^']+\.(?:yml|yaml))':$/, line) ->
        [_, path] = match
        put_workflow(state, path, true, line_number)

      match = Regex.run(~r/^        - '([^']+)'$/, line) ->
        [_, ref] = match
        put_workflow_ref(state, ref, line_number)

      true ->
        line_error(line_number, :malformed_workflow_entry)
    end
  end

  defp consume_line(line, line_number, %{section: :dependencies} = state) do
    cond do
      match = Regex.run(~r/^    '([^']+)':$/, line) ->
        [_, key] = match

        with {:ok, finalized} <- finalize_dependency(state) do
          if Regex.match?(@dependency_key, key) do
            {:ok, %{finalized | current_dependency: {key, %{}, line_number}}}
          else
            line_error(line_number, {:malformed_dependency_key, key})
          end
        end

      match = Regex.run(~r/^        ref: '([^']+)'$/, line) ->
        [_, ref] = match
        put_dependency_field(state, :ref, ref, line_number)

      match = Regex.run(~r/^        commit: 'sha1-([0-9A-Fa-f]{40})'$/, line) ->
        [_, commit] = match
        put_dependency_field(state, :commit, String.downcase(commit), line_number)

      Regex.match?(~r/^        commit:/, line) ->
        line_error(line_number, :malformed_dependency_commit)

      match = Regex.run(~r/^        (owner_id|repo_id): ([0-9]+)$/, line) ->
        [_, field, value] = match
        parsed = String.to_integer(value)

        if parsed > 0 do
          put_dependency_field(state, identity_field(field), parsed, line_number)
        else
          line_error(line_number, {:nonpositive_dependency_identity, field})
        end

      Regex.match?(~r/^        (?:owner_id|repo_id):/, line) ->
        line_error(line_number, :malformed_dependency_identity)

      line == "        uses:" ->
        put_dependency_field(state, :uses, MapSet.new(), line_number)

      match = Regex.run(~r/^            - '([^']+)'$/, line) ->
        [_, ref] = match

        if Regex.match?(@action_ref, ref) do
          put_transitive_ref(state, ref, line_number)
        else
          line_error(line_number, {:malformed_transitive_ref, ref})
        end

      true ->
        line_error(line_number, :malformed_dependency_entry)
    end
  end

  defp put_workflow(state, path, has_items, line_number) do
    if Map.has_key?(state.workflows, path) do
      line_error(line_number, {:duplicate_workflow, path})
    else
      current = if has_items, do: path, else: nil

      {:ok,
       %{
         state
         | workflows: Map.put(state.workflows, path, MapSet.new()),
           current_workflow: current
       }}
    end
  end

  defp put_workflow_ref(%{current_workflow: nil}, _ref, line_number) do
    line_error(line_number, :workflow_ref_without_workflow)
  end

  defp put_workflow_ref(state, ref, line_number) do
    if Regex.match?(@action_ref, ref) do
      normalized = normalise_ref(ref)
      refs = Map.fetch!(state.workflows, state.current_workflow)

      if MapSet.member?(refs, normalized) do
        line_error(line_number, {:duplicate_workflow_ref, state.current_workflow, ref})
      else
        workflows = Map.put(state.workflows, state.current_workflow, MapSet.put(refs, normalized))
        {:ok, %{state | workflows: workflows}}
      end
    else
      line_error(line_number, {:malformed_workflow_ref, ref})
    end
  end

  defp put_dependency_field(%{current_dependency: nil}, _field, _value, line_number) do
    line_error(line_number, :dependency_field_without_dependency)
  end

  defp put_dependency_field(state, field, value, line_number) do
    {key, dependency, header_line} = state.current_dependency

    if Map.has_key?(dependency, field) do
      line_error(line_number, {:duplicate_dependency_field, key, field})
    else
      {:ok, %{state | current_dependency: {key, Map.put(dependency, field, value), header_line}}}
    end
  end

  defp identity_field("owner_id"), do: :owner_id
  defp identity_field("repo_id"), do: :repo_id

  defp put_transitive_ref(%{current_dependency: nil}, _ref, line_number) do
    line_error(line_number, :dependency_detail_without_dependency)
  end

  defp put_transitive_ref(state, ref, line_number) do
    {key, dependency, header_line} = state.current_dependency

    case Map.fetch(dependency, :uses) do
      :error ->
        line_error(line_number, {:transitive_ref_without_uses, key})

      {:ok, uses} ->
        normalized = normalise_ref(ref)

        if MapSet.member?(uses, normalized) do
          line_error(line_number, {:duplicate_transitive_ref, key, ref})
        else
          updated = Map.put(dependency, :uses, MapSet.put(uses, normalized))
          {:ok, %{state | current_dependency: {key, updated, header_line}}}
        end
    end
  end

  defp finalize_dependency(%{current_dependency: nil} = state), do: {:ok, state}

  defp finalize_dependency(state) do
    {key, dependency, header_line} = state.current_dependency
    normalized = normalise_ref(key)

    with {:ok, ref} <- fetch_dependency_field(dependency, :ref, key, header_line),
         {:ok, commit} <- fetch_dependency_field(dependency, :commit, key, header_line),
         {:ok, owner_id} <- fetch_dependency_field(dependency, :owner_id, key, header_line),
         {:ok, repo_id} <- fetch_dependency_field(dependency, :repo_id, key, header_line),
         :ok <- validate_dependency_consistency(key, ref, commit, header_line),
         :ok <-
           validate_repository_identity(
             state.dependencies,
             normalized,
             owner_id,
             repo_id,
             header_line
           ),
         false <- Map.has_key?(state.dependencies, normalized) do
      stored = %{
        ref: ref,
        commit: commit,
        owner_id: owner_id,
        repo_id: repo_id,
        uses: Map.get(dependency, :uses, MapSet.new())
      }

      {:ok,
       %{
         state
         | dependencies: Map.put(state.dependencies, normalized, stored),
           current_dependency: nil
       }}
    else
      true -> line_error(header_line, {:duplicate_dependency, key})
      {:error, _reason} = error -> error
    end
  end

  defp validate_repository_identity(dependencies, normalized, owner_id, repo_id, line_number) do
    [repository, _ref] = String.split(normalized, "@", parts: 2)
    [owner, _repo] = String.split(repository, "/", parts: 2)

    with :ok <- validate_owner_id(dependencies, owner, owner_id, line_number),
         :ok <- validate_repo_id(dependencies, repository, repo_id, line_number),
         :ok <- validate_repo_id_uniqueness(dependencies, repository, repo_id, line_number) do
      :ok
    end
  end

  defp validate_owner_id(dependencies, owner, owner_id, line_number) do
    existing =
      Enum.find(dependencies, fn {dependency_ref, _dependency} ->
        [repository, _ref] = String.split(dependency_ref, "@", parts: 2)
        [dependency_owner, _repo] = String.split(repository, "/", parts: 2)
        dependency_owner == owner
      end)

    case existing do
      nil ->
        :ok

      {_ref, %{owner_id: ^owner_id}} ->
        :ok

      {_ref, dependency} ->
        line_error(
          line_number,
          {:owner_identity_mismatch, owner, dependency.owner_id, owner_id}
        )
    end
  end

  defp validate_repo_id(dependencies, repository, repo_id, line_number) do
    existing =
      Enum.find(dependencies, fn {dependency_ref, _dependency} ->
        [dependency_repository, _ref] = String.split(dependency_ref, "@", parts: 2)
        dependency_repository == repository
      end)

    case existing do
      nil ->
        :ok

      {_ref, %{repo_id: ^repo_id}} ->
        :ok

      {_ref, dependency} ->
        line_error(
          line_number,
          {:repository_identity_mismatch, repository, dependency.repo_id, repo_id}
        )
    end
  end

  defp validate_repo_id_uniqueness(dependencies, repository, repo_id, line_number) do
    existing =
      Enum.find(dependencies, fn {dependency_ref, dependency} ->
        [dependency_repository, _ref] = String.split(dependency_ref, "@", parts: 2)
        dependency.repo_id == repo_id and dependency_repository != repository
      end)

    case existing do
      nil ->
        :ok

      {dependency_ref, _dependency} ->
        [other_repository, _ref] = String.split(dependency_ref, "@", parts: 2)

        line_error(
          line_number,
          {:repository_id_reused, repo_id, other_repository, repository}
        )
    end
  end

  defp fetch_dependency_field(dependency, field, key, line_number) do
    case Map.fetch(dependency, field) do
      {:ok, value} -> {:ok, value}
      :error -> line_error(line_number, {:missing_dependency_field, key, field})
    end
  end

  defp validate_dependency_consistency(key, declared_ref, commit, line_number) do
    [_path, key_ref] = String.split(key, "@", parts: 2)

    cond do
      Regex.match?(@sha_ref, key_ref) and String.downcase(key_ref) != commit ->
        line_error(line_number, {:sha_key_commit_mismatch, key})

      not Regex.match?(@sha_ref, key_ref) and key_ref != declared_ref ->
        line_error(line_number, {:symbolic_key_ref_mismatch, key, declared_ref})

      true ->
        :ok
    end
  end

  defp finish({:error, _reason} = error), do: error

  defp finish({:ok, %{section: :dependencies} = state}) do
    with {:ok, finalized} <- finalize_dependency(state),
         :ok <- validate_workflow_dependencies(finalized),
         :ok <- validate_transitive_dependencies(finalized) do
      {:ok,
       %__MODULE__{
         version: finalized.version,
         workflows: finalized.workflows,
         dependencies: finalized.dependencies
       }}
    end
  end

  defp finish({:ok, _state}), do: {:error, :incomplete_lockfile}

  defp validate_transitive_dependencies(state) do
    missing =
      for {source, dependency} <- state.dependencies,
          target <- dependency.uses,
          not Map.has_key?(state.dependencies, target),
          do: {source, target}

    case missing do
      [] -> :ok
      entries -> {:error, {:transitive_dependencies_missing, Enum.sort(entries)}}
    end
  end

  defp validate_workflow_dependencies(state) do
    missing =
      for {path, refs} <- state.workflows,
          ref <- refs,
          not Map.has_key?(state.dependencies, ref),
          do: {path, ref}

    case missing do
      [] -> :ok
      entries -> {:error, {:workflow_dependencies_missing, Enum.sort(entries)}}
    end
  end

  defp line_error(line_number, reason), do: {:error, {:line, line_number, reason}}
end
