// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by hypatia-abi-gen from src/Hypatia/ABI/Types.idr
// ABI source blob: 788493e6f54b6d436ea551dbb5d34c6bc0d819ab
// DO NOT EDIT -- run `just abi-gen` and commit the result.

//! The sixteen-protocol wire contract, generated from the normative
//! Idris2 ABI. `connector.rs` re-exports these items and keeps its own
//! hand-written tests.

use serde::{Deserialize, Serialize};

/// A wire protocol supported by the Hypatia unified API adapter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[repr(u8)]
pub enum Connector {
    Grpc = 0,
    GraphQl = 1,
    Rest = 2,
    FlatBuffers = 3,
    Bebop = 4,
    JsonRpc = 5,
    WebSocket = 6,
    Mqtt = 7,
    Trpc = 8,
    CapnProto = 9,
    Soap = 10,
    VerisimdbRest = 11,
    Bsp = 12,
    Scip = 13,
    Ipfs = 14,
    ArrowFlight = 15,
}

/// Computed by the generator from `Hypatia.ABI.Types.allConnectors`.
pub const CONNECTOR_COUNT: usize = 16;

impl Connector {
    /// Stable wire name. Load-bearing: do not rename.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Grpc => "grpc",
            Self::GraphQl => "graphql",
            Self::Rest => "rest",
            Self::FlatBuffers => "flatbuffers",
            Self::Bebop => "bebop",
            Self::JsonRpc => "jsonrpc",
            Self::WebSocket => "websocket",
            Self::Mqtt => "mqtt",
            Self::Trpc => "trpc",
            Self::CapnProto => "capnproto",
            Self::Soap => "soap",
            Self::VerisimdbRest => "verisimdb-rest",
            Self::Bsp => "bsp",
            Self::Scip => "scip",
            Self::Ipfs => "ipfs",
            Self::ArrowFlight => "arrow-flight",
        }
    }

    /// Every connector, in wire order.
    #[must_use]
    pub const fn all() -> [Connector; CONNECTOR_COUNT] {
        [
            Connector::Grpc,
            Connector::GraphQl,
            Connector::Rest,
            Connector::FlatBuffers,
            Connector::Bebop,
            Connector::JsonRpc,
            Connector::WebSocket,
            Connector::Mqtt,
            Connector::Trpc,
            Connector::CapnProto,
            Connector::Soap,
            Connector::VerisimdbRest,
            Connector::Bsp,
            Connector::Scip,
            Connector::Ipfs,
            Connector::ArrowFlight,
        ]
    }

    /// Recover a connector from its C ABI wire id.
    #[must_use]
    pub fn from_id(id: u8) -> Option<Connector> {
        Self::all().get(id as usize).copied()
    }

    /// Port layout: `base_port + wire_id + 1`.
    #[must_use]
    pub const fn port(self, base_port: u16) -> u16 {
        base_port + (self as u8 as u16) + 1
    }
}
