# SPDX-License-Identifier: MPL-2.0

defmodule Hypatia.Rules.ActionsLockTest do
  use ExUnit.Case, async: true

  alias Hypatia.Rules.ActionsLock
  alias Hypatia.Rules

  @valid_lock """
  # This file is machine-generated by `gh actions-lock`.
  version: 'v0.0.2'
  workflows:
      '.github/workflows/ci.yml':
          - 'actions/checkout@v7.0.1'
      '.github/workflows/other.yml': []
  dependencies:
      'actions/checkout@v7.0.1':
          ref: 'v7.0.1'
          commit: 'sha1-3d3c42e5aac5ba805825da76410c181273ba90b1'
          owner_id: 44036562
          repo_id: 197814629
  """

  @workflow """
  permissions:
    contents: read
  jobs:
    test:
      steps:
        - uses: actions/checkout@v7.0.1
  """

  test "valid lock pins only the associated workflow and exact ref" do
    assert {:ok, lock} = ActionsLock.parse(@valid_lock)
    assert ActionsLock.pinned?(lock, "ci.yml", "actions/checkout@v7.0.1")
    assert ActionsLock.pinned?(lock, ".github/workflows/ci.yml", "Actions/Checkout@v7.0.1")

    refute ActionsLock.pinned?(lock, "other.yml", "actions/checkout@v7.0.1")
    refute ActionsLock.pinned?(lock, "ci.yml", "actions/checkout@v6.0.0")
  end

  test "accepts uppercase hexadecimal commit suffixes" do
    lock =
      String.replace(
        @valid_lock,
        "3d3c42e5aac5ba805825da76410c181273ba90b1",
        "3D3C42E5AAC5BA805825DA76410C181273BA90B1"
      )

    assert {:ok, parsed} = ActionsLock.parse(lock)
    assert ActionsLock.pinned?(parsed, "ci.yml", "actions/checkout@v7.0.1")
  end

  test "normalises repository identity but preserves case-sensitive refs" do
    lock = String.replace(@valid_lock, "v7.0.1", "ReleaseV7")

    assert {:ok, parsed} = ActionsLock.parse(lock)
    assert ActionsLock.pinned?(parsed, "ci.yml", "Actions/Checkout@ReleaseV7")
    refute ActionsLock.pinned?(parsed, "ci.yml", "actions/checkout@releasev7")
  end

  test "rejects missing, short, and non-hex commit fields" do
    missing = Regex.replace(~r/^\s*commit:.*\n/m, @valid_lock, "")

    short =
      String.replace(
        @valid_lock,
        "sha1-3d3c42e5aac5ba805825da76410c181273ba90b1",
        "sha1-1234"
      )

    non_hex =
      String.replace(
        @valid_lock,
        "sha1-3d3c42e5aac5ba805825da76410c181273ba90b1",
        "sha1-zd3c42e5aac5ba805825da76410c181273ba90b1"
      )

    assert {:error, {:line, _, {:missing_dependency_field, _, :commit}}} =
             ActionsLock.parse(missing)

    assert {:error, {:line, _, :malformed_dependency_commit}} = ActionsLock.parse(short)
    assert {:error, {:line, _, :malformed_dependency_commit}} = ActionsLock.parse(non_hex)
  end

  test "rejects unsupported versions and missing dependency entries" do
    assert {:error, {:line, 2, {:unsupported_version, "v9"}}} =
             @valid_lock
             |> String.replace("v0.0.2", "v9")
             |> ActionsLock.parse()

    missing_dependency = """
    version: 'v0.0.2'
    workflows:
        '.github/workflows/ci.yml':
            - 'actions/checkout@v7.0.1'
    dependencies:
    """

    assert {:error, {:workflow_dependencies_missing, [{_, "actions/checkout@v7.0.1"}]}} =
             ActionsLock.parse(missing_dependency)
  end

  test "rejects symbolic-ref and SHA-key contradictions" do
    symbolic = String.replace(@valid_lock, "ref: 'v7.0.1'", "ref: 'v6.0.0'")

    assert {:error, {:line, _, {:symbolic_key_ref_mismatch, _, _}}} =
             ActionsLock.parse(symbolic)

    sha_key = """
    version: 'v0.0.2'
    workflows:
        '.github/workflows/ci.yml':
            - 'actions/checkout@aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
    dependencies:
        'actions/checkout@aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa':
            ref: 'v7.0.1'
            commit: 'sha1-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
            owner_id: 44036562
            repo_id: 197814629
    """

    assert {:error, {:line, _, {:sha_key_commit_mismatch, _}}} = ActionsLock.parse(sha_key)
  end

  test "requires each positive repository identity exactly once" do
    for field <- [:owner_id, :repo_id] do
      missing = Regex.replace(~r/^\s*#{field}:.*\n/m, @valid_lock, "")

      assert {:error, {:line, _, {:missing_dependency_field, _, ^field}}} =
               ActionsLock.parse(missing)
    end

    zero = String.replace(@valid_lock, "owner_id: 44036562", "owner_id: 0")

    assert {:error, {:line, _, {:nonpositive_dependency_identity, "owner_id"}}} =
             ActionsLock.parse(zero)

    malformed = String.replace(@valid_lock, "repo_id: 197814629", "repo_id: unknown")
    assert {:error, {:line, _, :malformed_dependency_identity}} = ActionsLock.parse(malformed)

    duplicate =
      String.replace(
        @valid_lock,
        "owner_id: 44036562",
        "owner_id: 44036562\n        owner_id: 44036562"
      )

    assert {:error, {:line, _, {:duplicate_dependency_field, _, :owner_id}}} =
             ActionsLock.parse(duplicate)
  end

  test "rejects contradictory owner and repository identities" do
    contradictory_owner = """
    version: 'v0.0.2'
    workflows:
        '.github/workflows/ci.yml': []
    dependencies:
        'actions/checkout@v7':
            ref: 'v7'
            commit: 'sha1-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
            owner_id: 44036562
            repo_id: 197814629
        'actions/cache@v6':
            ref: 'v6'
            commit: 'sha1-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
            owner_id: 999
            repo_id: 215566462
    """

    assert {:error, {:line, _, {:owner_identity_mismatch, "actions", 44_036_562, 999}}} =
             ActionsLock.parse(contradictory_owner)

    contradictory_repo =
      contradictory_owner
      |> String.replace("'actions/cache@v6'", "'actions/checkout@v6'")
      |> String.replace("owner_id: 999", "owner_id: 44036562")

    assert {:error,
            {:line, _,
             {:repository_identity_mismatch, "actions/checkout", 197_814_629, 215_566_462}}} =
             ActionsLock.parse(contradictory_repo)
  end

  test "rejects a repository id reused by a different repository" do
    reused_id = """
    version: 'v0.0.2'
    workflows:
        '.github/workflows/ci.yml': []
    dependencies:
        'actions/checkout@v7':
            ref: 'v7'
            commit: 'sha1-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
            owner_id: 44036562
            repo_id: 197814629
        'other/cache@v6':
            ref: 'v6'
            commit: 'sha1-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
            owner_id: 123
            repo_id: 197814629
    """

    assert {:error,
            {:line, _, {:repository_id_reused, 197_814_629, "actions/checkout", "other/cache"}}} =
             ActionsLock.parse(reused_id)
  end

  test "validates and resolves transitive dependency entries" do
    transitive = """
    version: 'v0.0.2'
    workflows:
        '.github/workflows/ci.yml':
            - 'owner/composite@v1'
    dependencies:
        'owner/composite@v1':
            ref: 'v1'
            commit: 'sha1-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
            owner_id: 1
            repo_id: 2
            uses:
                - 'other/child@bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
        'other/child@bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb':
            ref: 'v2'
            commit: 'sha1-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
            owner_id: 3
            repo_id: 4
    """

    assert {:ok, parsed} = ActionsLock.parse(transitive)

    assert parsed.dependencies["owner/composite@v1"].uses ==
             MapSet.new(["other/child@bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"])

    missing =
      Regex.replace(
        ~r/^    'other\/child@bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb':.*\z/ms,
        transitive,
        ""
      )

    assert {:error, {:transitive_dependencies_missing, [{"owner/composite@v1", _}]}} =
             ActionsLock.parse(missing)

    duplicate =
      String.replace(
        transitive,
        "            - 'other/child@bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'",
        "            - 'other/child@bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'\n" <>
          "            - 'other/child@bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'"
      )

    assert {:error, {:line, _, {:duplicate_transitive_ref, "owner/composite@v1", _}}} =
             ActionsLock.parse(duplicate)
  end

  test "rejects non-canonical dependency keys" do
    subpath_key =
      String.replace(
        @valid_lock,
        "    'actions/checkout@v7.0.1':\n",
        "    'actions/checkout/subpath@v7.0.1':\n"
      )

    colon_key =
      String.replace(
        @valid_lock,
        "    'actions/checkout@v7.0.1':\n",
        "    'actions/checkout@refs:heads/main':\n"
      )

    assert {:error, {:line, _, {:malformed_dependency_key, _}}} =
             ActionsLock.parse(subpath_key)

    assert {:error, {:line, _, {:malformed_dependency_key, _}}} = ActionsLock.parse(colon_key)
  end

  test "parses the repository's authoritative generated lockfile" do
    content = File.read!(".github/workflows/actions.lock")
    assert {:ok, parsed} = ActionsLock.parse(content)
    assert map_size(parsed.workflows) > 0
    assert map_size(parsed.dependencies) > 0
  end

  test "legacy Rules workflow scanner delegates to path-aware lock semantics" do
    assert Rules.scan_workflow(@workflow, filename: "ci.yml", actions_lock: @valid_lock) == []

    findings = Rules.scan_workflow(@workflow, filename: "other.yml", actions_lock: @valid_lock)
    assert Enum.any?(findings, &(&1.rule == "unpinned_action"))

    malformed = String.replace(@valid_lock, ~r/sha1-[0-9a-f]{40}/, "sha1-short")
    findings = Rules.scan_workflow(@workflow, filename: "ci.yml", actions_lock: malformed)
    assert Enum.any?(findings, &(&1.rule == "invalid_actions_lock"))
    refute Enum.any?(findings, &(&1.rule == "unpinned_action"))
  end
end
