-- SPDX-License-Identifier: MPL-2.0
-- Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
--
-- Hypatia ABI — wire-contract code generator.
--
-- Emits the Zig `Connector` enum, the Rust `Connector` enum and the
-- `ffi/connectors.json` wire manifest from the *normative* Idris2 ABI in
-- `Hypatia.ABI.Types`.
--
-- This module **evaluates** `allConnectors`, `connectorWireId`,
-- `connectorName` and `connectorPort`. It never parses `.idr` text, so the
-- generated artefacts cannot disagree with the type that produced them.
--
-- The two naming functions (`zigIdent`, `rustIdent`) live here rather than in
-- `Hypatia.ABI.Types`: the normative ABI must not know about its consumers.
-- Both are total with one clause per constructor, so adding a seventeenth
-- connector without naming it is a *compile* error -- strictly stronger than
-- a CI diff.
--
-- Usage:  hypatia-abi-gen --out-dir <dir> --abi-hash <hex>

module Hypatia.ABI.Gen

import Hypatia.ABI.Types

import Data.List
import Data.String
import System
import System.File

%default total

--------------------------------------------------------------------------------
-- Small helpers
--------------------------------------------------------------------------------

||| Join with a separator. (Avoids depending on a particular `base` revision's
||| spelling of `joinBy`.)
joinWith : String -> List String -> String
joinWith sep xs = concat (intersperse sep xs)

||| Render a list of lines, newline-terminated.
lines' : List String -> String
lines' xs = joinWith "\n" xs ++ "\n"

quoted : String -> String
quoted s = "\"" ++ s ++ "\""

--------------------------------------------------------------------------------
-- Consumer-side naming
--------------------------------------------------------------------------------

||| Zig `enum(u8)` member names, snake_case.
|||
||| Transcribed verbatim from `ffi/zig/src/unified-api-adapter.zig` as it stood
||| before generation. These are a public wire-adjacent API: do not rename.
||| Note they are NOT derivable from `connectorName` in general -- the
||| relationship happens to be `-` -> `_` today, and stating it as a rule would
||| bake an accident into the generator.
public export
zigIdent : Connector -> String
zigIdent GRPC          = "grpc"
zigIdent GraphQL       = "graphql"
zigIdent REST          = "rest"
zigIdent FlatBuffers   = "flatbuffers"
zigIdent Bebop         = "bebop"
zigIdent JsonRpc       = "jsonrpc"
zigIdent WebSocket     = "websocket"
zigIdent MQTT          = "mqtt"
zigIdent TRPC          = "trpc"
zigIdent CapnProto     = "capnproto"
zigIdent SOAP          = "soap"
zigIdent VeriSimDBRest = "verisimdb_rest"
zigIdent BSP           = "bsp"
zigIdent SCIP          = "scip"
zigIdent IPFS          = "ipfs"
zigIdent ArrowFlight   = "arrow_flight"

||| Rust `#[repr(u8)]` variant names, UpperCamelCase.
|||
||| Transcribed verbatim from `clients/rust/hypatia-client/src/connector.rs`.
||| Genuinely not derivable: `GRPC` -> `Grpc`, `GraphQL` -> `GraphQl`,
||| `VeriSimDBRest` -> `VerisimdbRest`.
public export
rustIdent : Connector -> String
rustIdent GRPC          = "Grpc"
rustIdent GraphQL       = "GraphQl"
rustIdent REST          = "Rest"
rustIdent FlatBuffers   = "FlatBuffers"
rustIdent Bebop         = "Bebop"
rustIdent JsonRpc       = "JsonRpc"
rustIdent WebSocket     = "WebSocket"
rustIdent MQTT          = "Mqtt"
rustIdent TRPC          = "Trpc"
rustIdent CapnProto     = "CapnProto"
rustIdent SOAP          = "Soap"
rustIdent VeriSimDBRest = "VerisimdbRest"
rustIdent BSP           = "Bsp"
rustIdent SCIP          = "Scip"
rustIdent IPFS          = "Ipfs"
rustIdent ArrowFlight   = "ArrowFlight"

--------------------------------------------------------------------------------
-- Provenance banner
--------------------------------------------------------------------------------

||| SPDX must be the first line of every emitted file: the repository's
||| `validate-spdx.sh` pre-commit hook does not know these files are generated.
banner : (comment : String) -> (abiHash : String) -> List String
banner c abiHash =
  [ c ++ " SPDX-License-Identifier: MPL-2.0"
  , c ++ " Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>"
  , c
  , c ++ " @generated by hypatia-abi-gen from src/Hypatia/ABI/Types.idr"
  , c ++ " ABI source blob: " ++ abiHash
  , c ++ " DO NOT EDIT -- run `just abi-gen` and commit the result."
  ]

--------------------------------------------------------------------------------
-- Zig
--------------------------------------------------------------------------------

zigFile : (abiHash : String) -> String
zigFile abiHash = lines' $
  banner "//" abiHash ++
  [ ""
  , "//! The sixteen-protocol wire contract, generated from the normative"
  , "//! Idris2 ABI. `unified-api-adapter.zig` re-exports these declarations"
  , "//! and keeps its own hand-written tests."
  , ""
  , "pub const Connector = enum(u8) {"
  ] ++ map enumMember allConnectors ++
  [ ""
  , "    /// Stable wire name. Load-bearing: do not rename."
  , "    pub fn name(self: Connector) [*:0]const u8 {"
  , "        return switch (self) {"
  ] ++ map nameArm allConnectors ++
  [ "        };"
  , "    }"
  , ""
  , "    /// The connector's implementation module, selected at comptime."
  , "    pub fn module(comptime self: Connector) type {"
  , "        return switch (self) {"
  ] ++ map moduleArm allConnectors ++
  [ "        };"
  , "    }"
  , "};"
  , ""
  , "/// Derived from the enum itself, never a hand-written literal."
  , "pub const CONNECTOR_COUNT: usize = @typeInfo(Connector).@\"enum\".fields.len;"
  , ""
  , "/// Every connector, in wire order."
  , "pub const ALL: [CONNECTOR_COUNT]Connector = .{"
  ] ++ map allMember allConnectors ++
  [ "};"
  , ""
  , "/// Port layout: `base_port + wire_id + 1`."
  , "pub fn portFor(base_port: u16, c: Connector) u16 {"
  , "    return base_port + @as(u16, @intFromEnum(c)) + 1;"
  , "}"
  ]
  where
    enumMember : Connector -> String
    enumMember c = "    " ++ zigIdent c ++ " = " ++ show (connectorWireId c) ++ ","

    nameArm : Connector -> String
    nameArm c = "            ." ++ zigIdent c ++ " => " ++ quoted (connectorName c) ++ ","

    moduleArm : Connector -> String
    moduleArm c =
      "            ." ++ zigIdent c ++ " => @import(\"connectors/" ++ zigIdent c ++ ".zig\"),"

    allMember : Connector -> String
    allMember c = "    ." ++ zigIdent c ++ ","

--------------------------------------------------------------------------------
-- Rust
--------------------------------------------------------------------------------

rustFile : (abiHash : String) -> String
rustFile abiHash = lines' $
  banner "//" abiHash ++
  [ ""
  , "//! The sixteen-protocol wire contract, generated from the normative"
  , "//! Idris2 ABI. `connector.rs` re-exports these items and keeps its own"
  , "//! hand-written tests."
  , ""
  , "use serde::{Deserialize, Serialize};"
  , ""
  , "/// A wire protocol supported by the Hypatia unified API adapter."
  , "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]"
  , "#[repr(u8)]"
  , "pub enum Connector {"
  ] ++ map variant allConnectors ++
  [ "}"
  , ""
  , "/// Computed by the generator from `Hypatia.ABI.Types.allConnectors`."
  , "pub const CONNECTOR_COUNT: usize = " ++ show (length allConnectors) ++ ";"
  , ""
  , "impl Connector {"
  , "    /// Stable wire name. Load-bearing: do not rename."
  , "    #[must_use]"
  , "    pub const fn name(self) -> &'static str {"
  , "        match self {"
  ] ++ map nameArm allConnectors ++
  [ "        }"
  , "    }"
  , ""
  , "    /// Every connector, in wire order."
  , "    #[must_use]"
  , "    pub const fn all() -> [Connector; CONNECTOR_COUNT] {"
  , "        ["
  ] ++ map allMember allConnectors ++
  [ "        ]"
  , "    }"
  , ""
  , "    /// Recover a connector from its C ABI wire id."
  , "    #[must_use]"
  , "    pub fn from_id(id: u8) -> Option<Connector> {"
  , "        Self::all().get(id as usize).copied()"
  , "    }"
  , ""
  , "    /// Port layout: `base_port + wire_id + 1`."
  , "    #[must_use]"
  , "    pub const fn port(self, base_port: u16) -> u16 {"
  , "        base_port + (self as u8 as u16) + 1"
  , "    }"
  , "}"
  ]
  where
    variant : Connector -> String
    variant c = "    " ++ rustIdent c ++ " = " ++ show (connectorWireId c) ++ ","

    nameArm : Connector -> String
    nameArm c =
      "            Self::" ++ rustIdent c ++ " => " ++ quoted (connectorName c) ++ ","

    allMember : Connector -> String
    allMember c = "            Connector::" ++ rustIdent c ++ ","

--------------------------------------------------------------------------------
-- JSON
--------------------------------------------------------------------------------

||| JSON has no comments, so provenance lives in `_generated`.
jsonFile : (abiHash : String) -> String
jsonFile abiHash = lines' $
  [ "{"
  , "  \"_spdx\": \"MPL-2.0\","
  , "  \"_generated\": \"by hypatia-abi-gen from src/Hypatia/ABI/Types.idr; DO NOT EDIT -- run `just abi-gen` and commit the result\","
  , "  \"_abi_source_blob\": " ++ quoted abiHash ++ ","
  , "  \"_note\": \"Wire manifest for the unified-api-adapter. The normative source is the Idris2 ABI (src/Hypatia/ABI/Types.idr); this file, ffi/zig/src/connector_generated.zig and clients/rust/hypatia-client/src/connector_generated.rs are all generated from it. id is the C ABI wire id and ordering is load-bearing -- do not renumber by hand.\","
  , "  \"connectors\": ["
  , joinWith ",\n" (map entry allConnectors)
  , "  ]"
  , "}"
  ]
  where
    entry : Connector -> String
    entry c =
      "    { \"id\": " ++ show (connectorWireId c)
        ++ ", \"name\": " ++ quoted (connectorName c) ++ " }"

--------------------------------------------------------------------------------
-- Driver
--------------------------------------------------------------------------------

record Opts where
  constructor MkOpts
  outDir  : Maybe String
  abiHash : Maybe String

parseArgs : List String -> Opts -> Opts
parseArgs []                          acc = acc
parseArgs ("--out-dir"  :: v :: rest) acc = parseArgs rest ({ outDir  := Just v } acc)
parseArgs ("--abi-hash" :: v :: rest) acc = parseArgs rest ({ abiHash := Just v } acc)
parseArgs (_ :: rest)                 acc = parseArgs rest acc

writeOne : (path : String) -> (content : String) -> IO Bool
writeOne path content = do
  Right () <- writeFile path content
    | Left err => do
        putStrLn ("hypatia-abi-gen: cannot write " ++ path ++ ": " ++ show err)
        pure False
  pure True

emitAll : (outDir : String) -> (abiHash : String) -> IO ()
emitAll outDir abiHash = do
  ok1 <- writeOne (outDir ++ "/connector_generated.zig") (zigFile  abiHash)
  ok2 <- writeOne (outDir ++ "/connector_generated.rs")  (rustFile abiHash)
  ok3 <- writeOne (outDir ++ "/connectors.json")         (jsonFile abiHash)
  -- The denominator, per the standing vacuous-gate rule: a generator that
  -- cannot state how much it emitted is not evidence that it ran.
  putStrLn ("connectors emitted: " ++ show (length allConnectors))
  putStrLn ("files written:      " ++ show (length (filter id [ok1, ok2, ok3])) ++ " of 3")
  if ok1 && ok2 && ok3
    then pure ()
    else exitFailure

main : IO ()
main = do
  args <- getArgs
  let opts = parseArgs (drop 1 args) (MkOpts Nothing Nothing)
  case (opts.outDir, opts.abiHash) of
    (Just o, Just h) => emitAll o h
    _ => do
      putStrLn "usage: hypatia-abi-gen --out-dir <dir> --abi-hash <hex>"
      putStrLn ""
      putStrLn "  --out-dir   directory to write the three generated files into"
      putStrLn "  --abi-hash  `git hash-object src/Hypatia/ABI/Types.idr`"
      exitFailure
