#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# gen-rule-catalogue.sh — regenerate docs/rules/catalogue.adoc from lib/rules/*.ex
# so the published rule reference cannot drift from the code.
#
# Emits AsciiDoc natively. The catalogue was converted .md -> .adoc by the
# estate documentation sweep, but this generator kept writing the .md that
# no longer exists -- so "regenerate" silently produced an orphan file beside
# the real one and the catalogue drifted unnoticed. The conversion also
# dropped the SPDX header (C7 requires it on line 1); emitted here again.
#
# Monospace cells use the `+...+` passthrough form: rule modules are
# snake_case and AsciiDoc would otherwise treat a leading/trailing `_` as
# italic markup.
set -euo pipefail
cd "$(dirname "$0")/.."
out="docs/rules/catalogue.adoc"
mkdir -p docs/rules
{
  echo "// SPDX-License-Identifier: CC-BY-SA-4.0"
  echo "// GENERATED by scripts/gen-rule-catalogue.sh — do not edit by hand."
  echo
  echo "= Hypatia rule catalogue"
  echo
  echo "Generated from \`+lib/rules/*.ex+\` on $(date -u +%Y-%m-%d). Regenerate with:"
  echo
  echo "[source,bash]"
  echo "----"
  echo "./scripts/gen-rule-catalogue.sh"
  echo "----"
  echo
  echo "$(find lib/rules -maxdepth 1 -name '*.ex' | wc -l | tr -d ' ') rule modules. IDs are extracted from \`+rule:+\`/\`+id:+\` literals;"
  echo "a blank ID column means the module emits atom-keyed findings rather than prefixed IDs."
  echo
  echo '[cols="34,33,33",options="header"]'
  echo "|==="
  echo "|Module |Rule IDs |Purpose"
  for f in lib/rules/*.ex; do
    m=$(basename "$f" .ex)
    # `|| true` here is a no-match, not a discarded failure: many modules emit
    # atom-keyed findings and legitimately have no prefixed IDs.
    ids=$( { grep -ohE '(rule|id): "?[A-Z]{2,3}-?[A-Z]*-?[0-9]{3}"?' "$f" || true; } \
          | { grep -oE '[A-Z]{2,3}-?[A-Z]*-?[0-9]{3}' || true; } | sort -u | tr '\n' ' ' | sed 's/ $//')
    doc=$(awk '/@moduledoc """/{f=1;next} f&&/"""/{exit} f{gsub(/^[ \t]+/,""); if($0!="") {print; exit}}' "$f" \
          | sed 's/|/\\|/g' | cut -c1-140)
    # shellcheck disable=SC2016  # printf format string: literal by design
    printf '|`+%s+` |%s |%s\n' "$m" "${ids:-—}" "${doc:-—}"
  done
  echo "|==="
} > "$out"
echo "wrote $out"
